### ISSUE TITLE
Full Launch Checklist

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/scribes-of-the-cairo-geniza#92]
HOME PAGE
- [x] Need to grey out all workflows for pre-launch -- Penn team have PR starting on June 11, and they would like the site to be accessible (via URLs in those articles) but not functional (all buttons greyed-out for the time being). This will then be removed before full launch. (see below for screenshot of links that need to be disabled) #99 ![example](http://i64.tinypic.com/5vrqco.png) ![example](http://i65.tinypic.com/1z3135d.png)
- [x] Update "TRANSCRIBE" dropdown -- remove full list of options & reduce selections to "Continue Saved Work" or "Start a New Transcription". The latter option opens a list of workflows, including Classification & Keyword Search (similar to the boxes available on the Home page). #84 
- [x] Typo in the "What is Zooniverse?" paragraph: "discoeries" is missing the letter V (should read "discoveries") #98 
- [x] Remove duplicate logo for Cambridge ![example](http://i63.tinypic.com/n3u5ns.png) #98 
- [x] Replace current Princeton logo ("Princeton Geniza Project") with logo at 
https://drive.google.com/file/d/1rS7I3PAxvAA4Bx9SoTmyUqWWf3mZ_Ayu/view #98
- [x] Replace current "e-Lijah lab" logo with **two** Haifa logos (one for e-Lijah lab, one for Genizah Research Centre): https://drive.google.com/drive/folders/1G-L1_8S2Q47yirRBAzOPgYa2vevLkXBN #98
- [x] New Home Page intro text: https://docs.google.com/document/d/15iTcVfi7UKiPGI0MQxTQy_kC2bvFW6kvbTbkzdyeAzo/edit?usp=sharing #98 
- [x] New Special Thanks text: https://docs.google.com/document/d/1Jvff6XdZiOySPsOJ1FNC72t16k7Ow3re8h1Y0hsYHyM/edit?usp=sharing #98 

TRANSCRIPTION INTERFACE
- [x] When you click on an existing transcription (to revise your work), you can't press "Done" until you've changed something. This is a problem if a user wants to review a transcription, but changes their mind & doesn't want to edit the text -- they can't press Done. #84 
- [x] Crib sheet list appearing off the bottom edge of the modal #94  ![example](http://i67.tinypic.com/105xop2.png)
- [x] Add external link icon to "Library Catalog Page" link in Subject Info menu #98 

TRANSCRIPTION MODAL
- [ ] Needs to be set to pop up BENEATH annotation dots (this is a priority -- tons of beta feedback about this)
- [x] Arabic workflow only -- remove "Check out examples of different alphabets in the Crib Sheet" from this transcription pop-up box, since there's no Script References section for Arabic. (see below) #94  ![example](http://i64.tinypic.com/2ezpyq8.png)
- [x] Change "Close Keyboard" button to match Hebrew & Arabic options #98 

KEYBOARDS
- [x] Need to change order in which scripts appear in the _keyboard_ list (currently alphabetical, beginning with Ashkenazi Square): #98 ![example](http://i67.tinypic.com/2v36002.png)
Please update to:
- Oriental SW (Square, Cursive)
- Oriental NE (Square, Miniscule)
- Sephardi (Square, Miniscule, Cursive)
- Maghrebi (Square, Cursive)
- Yemenite (Square, Miniscule)
- Byzantine (Square, Miniscule, Cursive)
- Italian (Square, Miniscule, Cursive)
- Ashkenazi (Square, Miniscule, Cursive)

**Comment by shaunanoordin** [comment]
Now that #98 is merged, this issue is ready to be closed.

The only item remaining in this list is _"TRANSCRIPTION MODAL - Needs to be set to pop up BENEATH annotation dots"_ but as Will pointed out, this is a separate issue - I've opened #101 to keep track of it.
